import type { RacerCard, RacerName } from './types.js';

export const RACER_CARDS: Record<RacerName, RacerCard> = {
  alchemist: { name: 'alchemist', displayName: 'Alchemist', displayNameCn: '炼金术士', abilityText: 'When I roll a 1 or 2 for my main move, I can move 4 instead.', tagline: "TRANSMUTE 'N' SCOOT" },
  baba_yaga: { name: 'baba_yaga', displayName: 'Baba Yaga', displayNameCn: '芭芭雅嘎', abilityText: 'Trip any racer that stops on my space, or when I stop on theirs.', tagline: 'LEG IT' },
  banana: { name: 'banana', displayName: 'Banana', displayNameCn: '香蕉', abilityText: 'When a racer passes me, they trip.', tagline: 'THE SLIP' },
  blimp: { name: 'blimp', displayName: 'Blimp', displayNameCn: '飞艇', abilityText: 'When I start my turn before the second corner of the track, I get +3 to my main move. On or after that corner, I get -1.', tagline: 'BLOW IT' },
  centaur: { name: 'centaur', displayName: 'Centaur', displayNameCn: '半人马', abilityText: 'When I pass a racer, they move -2.', tagline: 'HOOFWHACK' },
  cheerleader: { name: 'cheerleader', displayName: 'Cheerleader', displayNameCn: '啦啦队长', abilityText: 'At the start of my turn, I can make the racer(s) in last place move 2. If I do, I move 1.', tagline: 'RAH RAH' },
  coach: { name: 'coach', displayName: 'Coach', displayNameCn: '教练', abilityText: 'Everyone on my space gets +1 to their main move, including me.', tagline: 'GOOD HUSTLE' },
  copy_cat: { name: 'copy_cat', displayName: 'Copy Cat', displayNameCn: '模仿猫', abilityText: "I have the power of the racer currently in the lead. If there's a tie, I pick.", tagline: 'COPY THAT' },
  dicemonger: { name: 'dicemonger', displayName: 'Dicemonger', displayNameCn: '骰子商人', abilityText: 'Anyone can reroll their main move once per turn. When another racer does it, I move 1.', tagline: 'DICEY DEALS' },
  duelist: { name: 'duelist', displayName: 'Duelist', displayNameCn: '决斗者', abilityText: 'Whenever a racer shares my space, I can shout DUEL! We roll our dice and whoever rolls highest moves 2. I win ties.', tagline: 'DUEL!' },
  egg: { name: 'egg', displayName: 'Egg', displayNameCn: '蛋', abilityText: 'At the start of my race, draw 3 new racers from the deck and pick one. I have its powers.', tagline: 'SCRAMBLE' },
  flip_flop: { name: 'flip_flop', displayName: 'Flip Flop', displayNameCn: '翻转拖鞋', abilityText: 'I can skip rolling for my main move and swap spaces with another racer instead.', tagline: 'FLOP FLIP' },
  genius: { name: 'genius', displayName: 'Genius', displayNameCn: '天才', abilityText: "I can predict what number I'll roll for my main move. If I'm right, I take another turn after this one.", tagline: 'THINK GOOD' },
  gunk: { name: 'gunk', displayName: 'Gunk', displayNameCn: '黏液怪', abilityText: 'Other racers get -1 to their main move.', tagline: "GOOP 'EM" },
  hare: { name: 'hare', displayName: 'Hare', displayNameCn: '兔子', abilityText: 'I get +2 to my main move. When I start my turn alone in the lead, I skip my move and get a bronze point chip.', tagline: 'HUBRIS' },
  heckler: { name: 'heckler', displayName: 'Heckler', displayNameCn: '起哄者', abilityText: 'When a racer ends their turn within 1 space of where they started, I move 2.', tagline: 'SCHADENFREUDE' },
  hypnotist: { name: 'hypnotist', displayName: 'Hypnotist', displayNameCn: '催眠师', abilityText: 'At the start of my turn, I can warp a racer to my space.', tagline: 'HSSSSST' },
  huge_baby: { name: 'huge_baby', displayName: 'Huge Baby', displayNameCn: '巨婴', abilityText: 'No one can ever be on my space, besides the Start. Whenever that would happen, put the racer on the space behind me instead.', tagline: 'REALLY HUGE' },
  inchworm: { name: 'inchworm', displayName: 'Inchworm', displayNameCn: '尺蠖虫', abilityText: 'When another racer rolls a 1 for their main move, they skip that move and I move 1.', tagline: 'WRIGGLE' },
  lackey: { name: 'lackey', displayName: 'Lackey', displayNameCn: '跟班', abilityText: 'When another racer rolls a 6 for their main move, I move 2 before they move.', tagline: 'VERY GOOD SIRE' },
  legs: { name: 'legs', displayName: 'Legs', displayNameCn: '长腿', abilityText: 'I can skip rolling for my main move and move 5 instead.', tagline: 'JOG' },
  leaptoad: { name: 'leaptoad', displayName: 'Leaptoad', displayNameCn: '跳蛙', abilityText: 'While moving, I skip spaces with other racers on them.', tagline: 'JUMPFROG' },
  lovable_loser: { name: 'lovable_loser', displayName: 'Lovable Loser', displayNameCn: '可爱的失败者', abilityText: "At the start of my turn, I get a bronze point chip if I'm alone in last place.", tagline: "D'AWW" },
  mouth: { name: 'mouth', displayName: 'M.O.U.T.H.', displayNameCn: '大嘴巴', abilityText: "When I stop on a space with exactly one other racer, they're eliminated from the race.", tagline: 'CHOMP' },
  magician: { name: 'magician', displayName: 'Magician', displayNameCn: '魔术师', abilityText: 'I can reroll my main move twice.', tagline: 'POOF' },
  mastermind: { name: 'mastermind', displayName: 'Mastermind', displayNameCn: '策划大师', abilityText: "At the start of my first turn, I predict which racer will win. If I'm right, the race ends immediately and I finish 2nd.", tagline: 'KNOW-IT-ALL' },
  party_animal: { name: 'party_animal', displayName: 'Party Animal', displayNameCn: '派对动物', abilityText: 'At the start of my turn, all racers move 1 space towards me. Each other racer on my space gives me +1 to my main move.', tagline: 'ANIMAL MAGNETISM' },
  rocket_scientist: { name: 'rocket_scientist', displayName: 'Rocket Scientist', displayNameCn: '火箭科学家', abilityText: 'When I roll for my main move, I can move double that number. If I do, I trip.', tagline: 'KABLOOEY' },
  romantic: { name: 'romantic', displayName: 'Romantic', displayNameCn: '浪漫者', abilityText: 'When anyone stops on a space with exactly one other racer, I move 2.', tagline: 'AH, LOVE!' },
  third_wheel: { name: 'third_wheel', displayName: 'Third Wheel', displayNameCn: '电灯泡', abilityText: 'Before my main move, I can warp to any space with exactly 2 racers in it.', tagline: 'ROLL THROUGH' },
  twin: { name: 'twin', displayName: 'Twin', displayNameCn: '双胞胎', abilityText: 'At the start of my race, I can pick a racer who won a previous race and race with their abilities.', tagline: 'DOUBLE DIP' },
  scoocher: { name: 'scoocher', displayName: 'Scoocher', displayNameCn: '蹭蹭狗', abilityText: "When another racer's power happens, I move 1.", tagline: 'SCOOCH SCOOCH' },
  skipper: { name: 'skipper', displayName: 'Skipper', displayNameCn: '船长', abilityText: 'When anyone rolls a 1 for their main move, I go next in turn order.', tagline: 'SALTY DOG' },
  suckerfish: { name: 'suckerfish', displayName: 'Suckerfish', displayNameCn: '吸盘鱼', abilityText: 'When a racer on my space moves, I can also move to their new space.', tagline: 'SUCKER!' },
  sisyphus: { name: 'sisyphus', displayName: 'Sisyphus', displayNameCn: '西西弗斯', abilityText: 'Before my race, I take 4 point chips. When I roll a 6 for my main move, instead of moving, I warp to the Start and lose 1 point chip.', tagline: "KEEP ROLLIN'" },
  stickler: { name: 'stickler', displayName: 'Stickler', displayNameCn: '较真者', abilityText: "Other racers can only cross the finish line by moving the exact amount they need. If they overshoot, they don't move.", tagline: 'ACTUALLY...' },
};

export const ALL_RACER_NAMES: RacerName[] = Object.keys(RACER_CARDS) as RacerName[];
